# Generated by Django 2.1.7 on 2019-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=10, verbose_name='性别'),
        ),
    ]
