# Generated by Django 2.1.7 on 2019-04-10 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=300, verbose_name='连接地址')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('author', models.CharField(default='', max_length=30, verbose_name='作者')),
                ('source', models.CharField(default='', max_length=30, verbose_name='来源')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('last_read_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上次阅读时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'db_table': 'notes',
            },
        ),
    ]
