# Generated by Django 2.1.7 on 2019-04-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
